### ISSUE TITLE
pronouns reload

### ISSUE THREAD

**Issue by kaliflowerx3** [kaliflowerx3/ZoltriTW#5]
25.04 07:50:59 [Server] ERROR null
25.04 07:50:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'pronouns' in plugin ZoltriTW v0.0.9
25.04 07:50:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:KCauldron-1.7.10-2.1403.1.54]
25.04 07:50:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:KCauldron-1.7.10-2.1403.1.54]
25.04 07:50:59 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:KCauldron-1.7.10-2.1403.1.54]
25.04 07:50:59 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
25.04 07:50:59 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
25.04 07:50:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
25.04 07:50:59 [Server] INFO Caused by: java.lang.NullPointerException
25.04 07:50:59 [Server] INFO at kaliflower.CustomConfig.reloadPronounsConfig(CustomConfig.java:25) ~[?:?]
25.04 07:50:59 [Server] INFO at kaliflower.Commands.PronsCommand.onCommand(PronsCommand.java:37) ~[?:?]
25.04 07:50:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:KCauldron-1.7.10-2.1403.1.54]

**Comment by jakeyray18** [comment]
Fixed - https://github.com/kaliflowerx3/ZoltriTW/commit/c2aaec3a8b339d5e569ab54e1bb4f3c980cb4e4f
